image:
  name: atlassian/default-image:2

pipelines:
    branches:
        master:
            - step:
                services:
                    - docker # Enable Docker for your repository
                name: Build and publish docker image.
                script:
                    # Modify the commands below to build your repository.
                    # Set the name of the docker image we will be building.
                    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    - unzip awscliv2.zip
                    - ./aws/install
                    - export IMAGE_NAME="intranet/${BITBUCKET_BRANCH}-reactjs-${BITBUCKET_REPO_SLUG}"
                    - docker build -t $IMAGE_NAME .
                    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 912708290344.dkr.ecr.us-east-1.amazonaws.com
                    - docker tag $IMAGE_NAME:latest 912708290344.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
                    - docker push 912708290344.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
                    - aws ecs update-service --service ${BITBUCKET_BRANCH}-${BITBUCKET_REPO_SLUG}-pocs --cluster ecs-cluster-production-us-east-1 --force-new-deployment

    branches:
        qa:
            - step:
                services:
                    - docker # Enable Docker for your repository
                name: Build and publish docker image.
                script:
                    # Modify the commands below to build your repository.
                    # Set the name of the docker image we will be building.
                    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    - unzip awscliv2.zip
                    - ./aws/install
                    - export IMAGE_NAME="intranetmu/${BITBUCKET_BRANCH}-reactjs-${BITBUCKET_REPO_SLUG}"
                    - docker build -t $IMAGE_NAME .
                    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 912708290344.dkr.ecr.us-east-1.amazonaws.com
                    - docker tag $IMAGE_NAME:latest 912708290344.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
                    - docker push 912708290344.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
                    - aws ecs update-service --service ${BITBUCKET_BRANCH}-${BITBUCKET_REPO_SLUG}-pocs --cluster ecs-cluster-production-us-east-1 --force-new-deployment

    branches:
        dev:
            - step:
                services:
                    - docker # Enable Docker for your repository
                name: Build and publish docker image.
                script:
                    # Modify the commands below to build your repository.
                    # Set the name of the docker image we will be building.
                    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    - unzip awscliv2.zip
                    - ./aws/install
                    - export IMAGE_NAME="intranet/${BITBUCKET_BRANCH}-reactjs-${BITBUCKET_REPO_SLUG}"
                    - docker build -t $IMAGE_NAME .
                    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 912708290344.dkr.ecr.us-east-1.amazonaws.com
                    - docker tag $IMAGE_NAME:latest 912708290344.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
                    - docker push 912708290344.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
                    - aws ecs update-service --service ${BITBUCKET_BRANCH}-${BITBUCKET_REPO_SLUG}-pocs --cluster ecs-cluster-production-us-east-1 --force-new-deployment
